root_dir: "/home/david/projects/completion_benchmarks/data"
raw_data_directory: "raw_data"
completion_directory: "completions"

cf_to_wf_npy_filename: "cf2gt.npy"
depth_cloud_name: "depth_cloud_cf.pcd"
tactile_cloud_name: "tactile_cloud_cf.pcd"
grid_size: 40

datasets:
  - "YCB_GRASP_590_Dataset_Test"
  - "Live_Test"

completions:
  - completion_name: "qhull"
    output_filename: "qhull_tactile_smoothed_completion.ply"
    include_tactile: true
  - completion_name: "marching_cubes"
    output_filename: "marching_cubes_tactile_smoothed_completion.ply"
    include_tactile: true

# Output directory will be:
# :root_dir:/:completion_directory:/:dataset_name:/:split_name:/:meshname:/:output_filename: